<?php

return [
    'id'          => 0,
    'id_str'      => '',
    'name'        => '',
    'screen_name' => '',
    'location'    => '',
    'description' => '',
    'url'         => '',
    'entities'    => [
        'url' => [
            'urls' => [
            ],
        ],
    ],
    'protected'                          => false,
    'followers_count'                    => 0,
    'friends_count'                      => 0,
    'listed_count'                       => 0,
    'created_at'                         => 'Tue May 11 17:48:52 +0000 2010',
    'favourites_count'                   => 0,
    'utc_offset'                         => null,
    'time_zone'                          => null,
    'geo_enabled'                        => false,
    'verified'                           => false,
    'statuses_count'                     => 0,
    'lang'                               => null,
    'status'                             => [],
    'contributors_enabled'               => false,
    'is_translator'                      => false,
    'is_translation_enabled'             => false,
    'profile_background_color'           => '',
    'profile_background_image_url'       => '',
    'profile_background_image_url_https' => '',
    'profile_background_tile'            => true,
    'profile_image_url'                  => '',
    'profile_image_url_https'            => '',
    'profile_banner_url'                 => '',
    'profile_link_color'                 => '',
    'profile_sidebar_border_color'       => '',
    'profile_sidebar_fill_color'         => '',
    'profile_text_color'                 => '',
    'profile_use_background_image'       => false,
    'has_extended_profile'               => false,
    'default_profile'                    => false,
    'default_profile_image'              => false,
    'following'                          => false,
    'follow_request_sent'                => false,
    'notifications'                      => false,
    'translator_type'                    => 'none',
];
